import time
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait

dr = webdriver.Chrome()
dr.implicitly_wait(10)
dr.get("file:///C:/Users/GQ/Desktop/page1/%E6%B3%A8%E5%86%8CA.html")
a = dr.find_element_by_id("userA")
time.sleep(1)
a.send_keys("admin1")
time.sleep(1)
a.send_keys(Keys.BACKSPACE)
time.sleep(1)
a.send_keys(Keys.CONTROL, "a")
time.sleep(1)
a.send_keys(Keys.CONTROL, "c")
time.sleep(1)
dr.find_element_by_id("passwordA").send_keys(Keys.CONTROL, "v")
time.sleep(1)
element = WebDriverWait(dr, 10, 0.1).until(lambda x: x.find_element_by_id("telA"))
element.send_keys("18012345678")
time.sleep(1)
ActionChains(dr).context_click(dr.find_element_by_id("userA")).perform()
time.sleep(1)
ActionChains(dr).move_to_element(dr.find_element_by_xpath("/html/body/div/fieldset/form/p[5]/button")).perform()
time.sleep(1)
dr.find_element_by_id("alerta").click()
time.sleep(1)
alert = dr.switch_to.alert
alert.accept()
time.sleep(1)
dr.find_element_by_id("confirma").click()
time.sleep(1)
alert.dismiss()
dr.find_element_by_id("prompta").click()
time.sleep(1)
alert.accept()
time.sleep(1)
dr.execute_script("window.scrollTo(0,100000)")
time.sleep(1)
dr.execute_script('window.scrollTo(0,0)')
time.sleep(1)
select=Select(dr.find_element_by_id("selectA"))
time.sleep(1)
select.select_by_visible_text("A上海")
time.sleep(1)
select.select_by_value("sh")
time.sleep(1)
select.select_by_index("3")
time.sleep(1)
dr.quit()
